title: "Needlehack"
baseurl: ""
url: "https://ivangrod.github.io"
theme: null
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
